GET https://labecommerce-revisao-z5nq.onrender.com/character
###
PUT https://labecommerce-revisao-z5nq.onrender.com/character

{
    "name": "Mauricio",
    "gender": "MALE"
}


###

DELETE https://labecommerce-revisao-z5nq.onrender.com/character/3