
GET https://labecommerce-revisao-nbcl.onrender.com/character
###
PUT https://labecommerce-revisao-nbcl.onrender.com/character
Content-Type: application/json


{
    "name": "Mauricio",
    "gender": "MALE"
}


###

DELETE https://labecommerce-revisao-z5nq.onrender.com/character/3

